# Generated by Django 5.2.4 on 2025-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Токен"
            ),
        ),
    ]
